import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:shop_app/providers/carts.dart';
import 'package:http/http.dart' as http;
import 'package:shop_app/widgets/cartitem.dart';

class OrderItem {
  final String id;
  final double amount;
  final List<cartItem> products;
  final DateTime date;

  OrderItem({this.id, this.amount, this.products, this.date});
}

class Orders with ChangeNotifier {
  List<OrderItem> _orders = [];

  List<OrderItem> get orders {
    return [..._orders];
  }

  Future<void> addOrders(List<cartItem> cartproducts, double total) async {
    const url =
        "https://shop-app-a70e5-default-rtdb.firebaseio.com/products.json";
    final timestamp = DateTime.now();
    final response = await http.post(Uri.parse(url),
        body: json.encode({
          "amount": total,
          "date": timestamp.toIso8601String(),
          "products": cartproducts.map((cp) => {
                "id": cp.id,
                "price": cp.price,
                "title": cp.title,
                "Quantity": cp.quantity,
              })
        }));

    _orders.insert(
        0,
        OrderItem(
            id: json.decode(response.body)["name"], //autogenerated id
            amount: total,
            date: timestamp,
            products: cartproducts));

    notifyListeners();
  }
}
